In [2]:
import numpy as np

In [32]:
eta = (np.arange(5) * 0.1).reshape(5,1)
h =  np.random.rand(5, 5)

In [33]:
eta * h

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [6.71961439e-02, 7.11696938e-03, 6.69932180e-02, 2.13006329e-02,
        3.00273837e-04],
       [5.38062584e-02, 1.91012479e-01, 1.88381880e-01, 2.34898771e-02,
        7.96526476e-02],
       [2.25019943e-01, 1.87291785e-01, 6.20069983e-03, 2.48175762e-01,
        2.35388050e-01],
       [2.59201371e-01, 3.08468805e-01, 2.82804225e-01, 1.87917221e-01,
        2.44621088e-01]])

In [34]:
eta

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4]])

In [35]:
h

array([[0.32945651, 0.40520211, 0.42757401, 0.64707391, 0.87876178],
       [0.67196144, 0.07116969, 0.66993218, 0.21300633, 0.00300274],
       [0.26903129, 0.9550624 , 0.9419094 , 0.11744939, 0.39826324],
       [0.75006648, 0.62430595, 0.020669  , 0.82725254, 0.78462683],
       [0.64800343, 0.77117201, 0.70701056, 0.46979305, 0.61155272]])

In [ ]:
networks = [[1,1],[1,0],[1,0.5],[0.5,0.5],[0.5,0]]
commands = [    
    'ML [50,50] [1,1] [M,A] 4',    
    'ML [50,50] [1,1] [M,M] 4',    
    'Dyn_RO [50,50] [1,1] [M,A] 4',    
    'Dyn_RO [50,50] [1,1] [M,M] 4',     
    'end',
]
modified_commands = []
for network in networks:
    for command in commands:
        modified_command = command.replace('[1,1]', str(network))
        modified_commands.append(modified_command)

from itertools import permutations
all_permutations = list(permutations(modified_commands, len(modified_commands)))


In [2]:
networks = [[1,1],[1,0],[1,0.5],[0.5,0.5],[0.5,0]]

commands = [    
    'ML [50,50] [1,1] [M,A] 4',    
    'ML [50,50] [1,1] [M,M] 4',    
    'Dyn_RO [50,50] [1,1] [M,A] 4',    
    'Dyn_RO [50,50] [1,1] [M,M] 4',     
    'end',
]

modified_commands = []
for network in networks:
    for command in commands:
        modified_command = command.replace('[1,1]', str(network))
        modified_commands.append(modified_command)

In [3]:
modified_commands

['ML [50,50] [1, 1] [M,A] 4',
 'ML [50,50] [1, 1] [M,M] 4',
 'Dyn_RO [50,50] [1, 1] [M,A] 4',
 'Dyn_RO [50,50] [1, 1] [M,M] 4',
 'end',
 'ML [50,50] [1, 0] [M,A] 4',
 'ML [50,50] [1, 0] [M,M] 4',
 'Dyn_RO [50,50] [1, 0] [M,A] 4',
 'Dyn_RO [50,50] [1, 0] [M,M] 4',
 'end',
 'ML [50,50] [1, 0.5] [M,A] 4',
 'ML [50,50] [1, 0.5] [M,M] 4',
 'Dyn_RO [50,50] [1, 0.5] [M,A] 4',
 'Dyn_RO [50,50] [1, 0.5] [M,M] 4',
 'end',
 'ML [50,50] [0.5, 0.5] [M,A] 4',
 'ML [50,50] [0.5, 0.5] [M,M] 4',
 'Dyn_RO [50,50] [0.5, 0.5] [M,A] 4',
 'Dyn_RO [50,50] [0.5, 0.5] [M,M] 4',
 'end',
 'ML [50,50] [0.5, 0] [M,A] 4',
 'ML [50,50] [0.5, 0] [M,M] 4',
 'Dyn_RO [50,50] [0.5, 0] [M,A] 4',
 'Dyn_RO [50,50] [0.5, 0] [M,M] 4',
 'end']